In [1]:

import pandas as pd
import numpy as np

# Data Viz library
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
df_FW = pd.read_csv(r'C:\Users\JayNB\OneDrive\เดสก์ท็อป\NIDA\ML_QUIZ\log2.csv')

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X = df_FW[['NAT Source Port','NAT Destination Port', 'Bytes','Packets','Elapsed Time (sec)']]
Y = df_FW['Action']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=55)

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
# ตั้งชื่อตัวแบบว่า "rf" ให้สุ่ม 500 trees  ให้กด Shift+Tabในวงเล็บ เพื่อดู Parameter ใน Algorithm

rf = RandomForestClassifier(n_estimators = 500)

In [8]:
rf = RandomForestClassifier()

In [9]:
rf.fit(X_train, y_train)

RandomForestClassifier()

In [10]:
# ทำนายค่าในชุด test set ที่แบ่งไว้ 30%

pre_rf = rf.predict(X_test)

In [11]:
# นำเข้า classification report และ confusion matrix

from sklearn.metrics import classification_report, confusion_matrix

In [12]:
# สั่งพิมพ์รายงาน ค่าการวัดผล และประสิทธิภาพการทำนายของตัวแบบ และค่าใน confusion matrix

print(classification_report(y_test, pre_rf))
print('\n')
print(confusion_matrix(y_test, pre_rf))

              precision    recall  f1-score   support

       allow       1.00      1.00      1.00     11378
        deny       0.77      1.00      0.87      4452
        drop       0.99      0.66      0.79      3811
  reset-both       1.00      0.32      0.48        19

    accuracy                           0.93     19660
   macro avg       0.94      0.74      0.79     19660
weighted avg       0.95      0.93      0.93     19660



[[11377     1     0     0]
 [    1  4432    19     0]
 [    0  1287  2524     0]
 [    0    13     0     6]]


In [16]:

from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE().fit_resample(X_train, y_train)

In [17]:
# แสดงจำนวนหลังสุ่ม OverSampling

print("After OverSampling, counts 'allow': {}".format(sum(y_resampled == "allow")))
print("After OverSampling, counts 'deny': {} ".format(sum(y_resampled == "deny")))
print("After OverSampling, counts 'drop': {} ".format(sum(y_resampled == "drop")))
print("After OverSampling, counts 'reset-both': {} \n".format(sum(y_resampled == "reset-both")))

After OverSampling, counts 'allow': 26262
After OverSampling, counts 'deny': 26262 
After OverSampling, counts 'drop': 26262 
After OverSampling, counts 'reset-both': 26262 



In [18]:
from sklearn.model_selection import train_test_split

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
# ตั้งชื่อตัวแบบที่ใช้ชุดข้อมูลสุ่มสมดุลว่า "rf_res" ให้สุ่ม 500 trees

rf_res = RandomForestClassifier(n_estimators = 500)

In [20]:
rf_res.fit(X_resampled, y_resampled)

RandomForestClassifier(n_estimators=500)

In [21]:
# List of features for later use
feature_list = list(X_train.columns)

# Get numerical feature importances
importances = list(rf_res.feature_importances_)

# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, 
                       importance in zip(feature_list, importances)]

# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)

# Print out the feature and importances 
[print('Variable: {:11} Importance: {}'.format(*pair)) for pair in feature_importances]

Variable: Bytes       Importance: 0.5
Variable: Elapsed Time (sec) Importance: 0.22
Variable: NAT Source Port Importance: 0.13
Variable: NAT Destination Port Importance: 0.11
Variable: Packets     Importance: 0.04


[None, None, None, None, None]

In [23]:
pre_rf_res = rf_res.predict(X_test)

In [24]:
print(classification_report(y_test, pre_rf_res))
print('\n')
print(confusion_matrix(y_test, pre_rf_res))

              precision    recall  f1-score   support

       allow       1.00      1.00      1.00     11378
        deny       1.00      0.56      0.72      4452
        drop       0.73      1.00      0.84      3811
  reset-both       0.03      0.79      0.05        19

    accuracy                           0.90     19660
   macro avg       0.69      0.84      0.65     19660
weighted avg       0.95      0.90      0.90     19660



[[11377     1     0     0]
 [    1  2486  1442   523]
 [    0     0  3811     0]
 [    0     4     0    15]]


In [25]:
from sklearn.model_selection import GridSearchCV

# Create the parameter grid based on the results of random search 
param_grid = {
    'max_features': [4,6,8],
    'min_samples_leaf': [1,3,5],
    'min_samples_split': [2,5,12],
    'n_estimators': [10,100,300,500]
}

# Create a based model
rf = RandomForestClassifier()

# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, verbose = 3)

In [26]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits
[CV 1/5] END max_features=4, min_samples_leaf=1, min_samples_split=2, n_estimators=10;, score=0.931 total time=   0.1s
[CV 2/5] END max_features=4, min_samples_leaf=1, min_samples_split=2, n_estimators=10;, score=0.930 total time=   0.0s
[CV 3/5] END max_features=4, min_samples_leaf=1, min_samples_split=2, n_estimators=10;, score=0.935 total time=   0.0s
[CV 4/5] END max_features=4, min_samples_leaf=1, min_samples_split=2, n_estimators=10;, score=0.938 total time=   0.1s
[CV 5/5] END max_features=4, min_samples_leaf=1, min_samples_split=2, n_estimators=10;, score=0.932 total time=   0.0s
[CV 1/5] END max_features=4, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.931 total time=   1.2s
[CV 2/5] END max_features=4, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.930 total time=   1.1s
[CV 3/5] END max_features=4, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.935 t

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'max_features': [4, 6, 8],
                         'min_samples_leaf': [1, 3, 5],
                         'min_samples_split': [2, 5, 12],
                         'n_estimators': [10, 100, 300, 500]},
             verbose=3)

In [28]:
best = grid_search.best_estimator_

In [29]:
rf_fine = best

In [30]:
rf_fine.fit(X_train, y_train)

RandomForestClassifier(max_features=6, n_estimators=10)

In [31]:
predictions = rf_fine.predict(X_test)

In [32]:
from sklearn.metrics import classification_report, confusion_matrix

In [33]:
print(classification_report(y_test, predictions))
print('\n')
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

       allow       1.00      1.00      1.00     11378
        deny       0.77      1.00      0.87      4452
        drop       0.99      0.66      0.79      3811
  reset-both       1.00      0.32      0.48        19

    accuracy                           0.93     19660
   macro avg       0.94      0.74      0.79     19660
weighted avg       0.95      0.93      0.93     19660



[[11377     1     0     0]
 [    1  4431    20     0]
 [    0  1287  2524     0]
 [    0    13     0     6]]


In [34]:
# Bagging: using all features

rf_bagged = RandomForestClassifier(max_features = 11, random_state = 55)

rf_bagged.fit(X_train, y_train)

RandomForestClassifier(max_features=11, random_state=55)

In [35]:
# ทำนายค่าในชุด test set ที่แบ่งไว้ 30%

predictions = rf_bagged.predict(X_train)

In [36]:
print(classification_report(y_train, predictions))
print('\n')
print(confusion_matrix(y_train, predictions))

              precision    recall  f1-score   support

       allow       1.00      1.00      1.00     26262
        deny       0.78      1.00      0.87     10535
        drop       0.99      0.67      0.80      9040
  reset-both       1.00      0.17      0.29        35

    accuracy                           0.93     45872
   macro avg       0.94      0.71      0.74     45872
weighted avg       0.95      0.93      0.93     45872



[[26253     9     0     0]
 [    0 10495    40     0]
 [    0  2969  6071     0]
 [    0    29     0     6]]
